//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanSach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GioHang
    {
        public int MaGH { get; set; }
        public Nullable<int> MaKH { get; set; }
        public Nullable<int> MaSach { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<System.DateTime> Thoigian { get; set; }
        public Nullable<double> ThanhTien { get; set; }
        public Nullable<int> MaDH { get; set; }
    
        public virtual HoaDon HoaDon { get; set; }
        public virtual KhachHang KhachHang { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
