//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanSach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HoaDon()
        {
            this.GioHangs = new HashSet<GioHang>();
        }
    
        public int MaHD { get; set; }
        public Nullable<int> MaKH { get; set; }
        public Nullable<System.DateTime> NgayLapHD { get; set; }
        public Nullable<double> TongTien { get; set; }
        public string TenKhach { get; set; }
        public string SDTDatHang { get; set; }
        public string EmailXacNhan { get; set; }
        public string DiaChiNhanHang { get; set; }
        public Nullable<int> GiamGia { get; set; }
        public Nullable<double> TongThanhToan { get; set; }
        public string TrangThai { get; set; }
        public Nullable<System.DateTime> NgayNhanHang { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GioHang> GioHangs { get; set; }
    }
}
